apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-admin-password
spec:
  length: 40
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  refreshInterval: "0"
  target:
    name: grafana-admin-credentials
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-admin-password
      rewrite:
        - regexp:
            source: ".*"
            target: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-telegram-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-telegram-alerting
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      metadata:
        labels:
          grafana_alert: "1"
      data:
        contactpoints.yaml: |
          apiVersion: 1
          contactPoints:
            - orgId: 1
              name: Telegram infrastructure
              receivers:
                - uid: telegram-infrastructure
                  type: telegram
                  disableResolveMessage: false
                  settings:
                    bottoken: "{{ .botToken }}"
                    chatid: "{{ .chatId }}"
                    disable_web_page_preview: true
                    parse_mode: HTML
                    message: '{{ "{{" }} template "telegram.message.ko" . {{ "}}" }}'
        policies.yaml: |
          apiVersion: 1
          policies:
            - orgId: 1
              receiver: Telegram infrastructure
              group_by:
                - grafana_folder
                - alertname
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 4h
  data:
    - secretKey: botToken
      remoteRef:
        key: /homelab/cluster/backbone/token/telegram/grafana
    - secretKey: chatId
      remoteRef:
        key: /homelab/cluster/backbone/chat-id/telegram/grafana-alerts
