apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-admin-password
spec:
  length: 40
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  refreshInterval: "0"
  target:
    name: grafana-admin-credentials
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-admin-password
      rewrite:
        - regexp:
            source: ".*"
            target: password
