apiVersion: objectstorage.k8s.io/v1alpha1
kind: Bucket
metadata:
  name: thanos
spec:
  bucketClaim:
    name: thanos
    namespace: prometheus
  bucketClassName: versitygw-hdd-cosi-driver
  driverName: versitygw-hdd.cosi.dev
  deletionPolicy: Retain
  protocols:
    - S3
