apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes
    kind: SecretStore
  target:
    name: thanos-objstore-config
    template:
      engineVersion: v2
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: thanos
            endpoint: versitygw-hdd.object-storage.svc:7070
            access_key: "{{ (.BucketInfo | fromJson).spec.secretS3.accessKeyID }}"
            secret_key: "{{ (.BucketInfo | fromJson).spec.secretS3.accessSecretKey }}"
            insecure: true
  data:
    - secretKey: BucketInfo
      remoteRef:
        key: thanos-bucket-creds
        property: BucketInfo
