{{- if and .Values.cloudflareOriginIssuer.enabled .Values.cloudflareOriginIssuer.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "argocd.fullname" . }}-cloudflare-api-token
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.cloudflareOriginIssuer.apiToken | quote }}
  template:
    data: null
    metadata:
      name: {{ include "argocd.fullname" . }}-cloudflare-api-token
      labels:
        {{- include "argocd.labels" . | nindent 8 }}
      namespace: {{ .Release.Namespace }}
{{- end }}