{{- if not .Values.cloudflareOriginIssuer.sealedSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.fullname" . }}-cloudflare-api-token
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.cloudflareOriginIssuer.apiToken | quote }}
{{- end }}