---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus
provisioner: nfs.csi.k8s.io
parameters:
  server: n2p2
  share: /mnt/k8s/prometheus
  mountPermissions: '0777'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
mountOptions:
  - nfsvers=4.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql
provisioner: nfs.csi.k8s.io
parameters:
  server: n2p2
  share: /mnt/k8s/mysql
  mountPermissions: '0755'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Retain
mountOptions:
  - nfsvers=4.2
