---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus
provisioner: nfs.csi.k8s.io
parameters:
  server: n2p2
  share: /mnt/k8s/prometheus
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-hot-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: n2p2
  share: /mnt/k8s
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: temporal
provisioner: nfs.csi.k8s.io
parameters:
  server: n2p1
  share: /mnt/temporal/k8s
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas
provisioner: nfs.csi.k8s.io
parameters:
  server: n2p1
  share: /mnt/data/k8s
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
