imagePullSecrets:
  - name: bhyoo-registry-key

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/issuer: cloudflare-origin-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    cert-manager.io/duration: 168h
    cert-manager.io/renew-before: 24h
  hosts:
    - host: jay.bhyoo.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - jay.bhyoo.com
      secretName: india-jay-com

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: false
  storageClass: ceph-block
