## CRD upgrade job to avoid ServerSideApply timeout on large CRDs
##
crds:
  upgradeJob:
    enabled: true

nameOverride: shared

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  enabled: false

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  grafana.ini:
    date_formats:
      default_timezone: Asia/Seoul

  ## Timezone for the default dashboards
  ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
  ##
  defaultDashboardsTimezone: Asia/Seoul

  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      cert-manager.io/cluster-issuer: cluster-issuer-acme
      cert-manager.io/private-key-algorithm: ECDSA
      cert-manager.io/private-key-size: '384'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

    hosts:
      - grafana.bhyoo.com

    ## Path for grafana ingress
    path: /

    tls:
      - secretName: grafana-general-tls
        hosts:
          - grafana.bhyoo.com

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      # Allow discovery in all namespaces for dashboards
      searchNamespace: ALL

      multicluster:
        global:
          enabled: true
        etcd:
          enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true

      uid: prometheus

      ## Set method for HTTP to send query to datasource
      httpMethod: POST

      label: grafana_datasource
      labelValue: "1"

      alertmanager:
        enabled: false

  ## Configure additional grafana datasources (passed through tpl)
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.loki.svc.cluster.local
      isDefault: false
      editable: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: community
          orgId: 1
          folder: Community
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/community

  dashboards:
    community:
      node-exporter-full:
        gnetId: 1860
        revision: 42
        datasource: Prometheus
      traefik:
        gnetId: 17346
        revision: 9
        datasource: Prometheus
      argocd:
        gnetId: 14584
        revision: 1
        datasource: Prometheus
      cert-manager:
        gnetId: 20842
        revision: 3
        datasource: Prometheus
      minio:
        gnetId: 13502
        revision: 26
        datasource: Prometheus

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  serviceMonitor:
    attachMetadata:
      node: true

## Component scraping etcd
##
kubeEtcd:
  enabled: true

  service:
    enabled: true
    port: 2381
    targetPort: 2381

  serviceMonitor:
    enabled: true
    scheme: http

## Component scraping kube proxy
##
kubeProxy:
  enabled: true

  service:
    enabled: true
    port: 10249
    targetPort: 10249

  serviceMonitor:
    enabled: true

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  nameOverride: node-exporter
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 64Mi

## Manages Prometheus and Alertmanager components
##
prometheusOperator:

  admissionWebhooks:
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded

    # Use certmanager to generate webhook certs
    certManager:
      enabled: true
      issuerRef:
        kind: ClusterIssuer
        name: cluster-issuer-self-signed

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi

## Deploy a Prometheus instance
##
prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer-acme
      cert-manager.io/private-key-algorithm: ECDSA
      cert-manager.io/private-key-size: '384'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

    hosts:
      - prometheus.bhyoo.com

    tls:
      - secretName: prometheus-general-tls
        hosts:
          - prometheus.bhyoo.com

  prometheusSpec:
    scrapeClasses:
      - name: default
        default: true
        relabelings:
          - targetLabel: cluster
            replacement: backbone
            action: replace

    ## External labels to add to any time series or alerts when communicating with external systems
    ##
    externalLabels:
      cluster: backbone

    ## enable --web.enable-remote-write-receiver flag on prometheus-server
    ##
    enableRemoteWriteReceiver: true

    ## How long to retain metrics
    ##
    retention: 10d

    ## Allow out-of-order/out-of-bounds samples ingested into Prometheus for a specified duration
    ## See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb
    tsdb:
      outOfOrderTimeWindow: 5m

    ## Resource limits & requests
    ##
    resources:
      requests:
        cpu: 200m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 6Gi

    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
    ##
    storageSpec:
      volumeClaimTemplate:
        metadata:
          annotations:
            democratic-csi.org/config: '{"zfs":{"zvolBlocksize":"16K","datasetProperties":{"compression":"lz4","dedup":"off","logbias":"throughput","sync":"standard","primarycache":"metadata","redundant_metadata":"most"}}}'
        spec:
          storageClassName: ssd-ha-xfs
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 256Gi

    securityContext:
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch

cleanPrometheusOperatorObjectNames: true
