## Provide a name in place of kube-prometheus-stack for `app:` labels
##
nameOverride: shared

## Create default rules for monitoring the cluster
##
defaultRules:
  create: false

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  enabled: false

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: false

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  namespace: kube-system

## Component scraping etcd
##
kubeEtcd:
  enabled: false

## Deploy a Prometheus instance
##
prometheus:
  ## Toggle prometheus into agent mode
  ## Note many of features described below (e.g. rules, query, alerting, remote read, thanos) will not work in agent mode.
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/platform/prometheus-agent.md
  ##
  agentMode: true

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#prometheusspec
  ##
  prometheusSpec:
    ## External labels to add to any time series or alerts when communicating with external systems
    ##
    externalLabels:
      cluster: prod

    ## The remote_write spec configuration for Prometheus.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#remotewritespec
    remoteWrite:
      - url: "https://prometheus.bhyoo.com/api/v1/write"
        name: backbone
