default_iface: eth0
locale_lang: ko_KR.UTF-8
locale_timezone: Asia/Seoul

# iptables-firewall
iptables_use_mdns: true
iptables_use_llmnr: true

# wireguard_mesh
wireguard_external_host: "backbone.bhyoo.com"

# cluster
k8s_registration_address: "k8s.backbone.homelab.bhyoo.com"
