apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-config
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: github-config
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: /homelab/cluster/backbone/token/github/arc-cc-lb
