apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-config
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: github-config
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: /homelab/cluster/backbone/github-app/arc-cc-lb/id
    - secretKey: github_app_installation_id
      remoteRef:
        key: /homelab/cluster/backbone/github-app/arc-cc-lb/installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: /homelab/cluster/backbone/github-app/arc-cc-lb/private-key
