apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        name: '{{name}}'
        namespace: cert-manager
      project: cert-manager
      sources:
        - repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          ref: homelab
        - chart: cert-manager
          helm:
            releaseName: cert-manager
            valueFiles:
              - values.yaml
              - '$homelab/values/cert-manager/{{name}}.yaml'
          repoURL: https://charts.jetstack.io
          targetRevision: v1.17.2
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-issuer-acme
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager-cluster-issuer'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        name: '{{name}}'
        namespace: cert-manager
      project: cert-manager
      sources:
        - repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          ref: homelab
        - chart: cluster-issuer
          helm:
            releaseName: cluster-issuer
            valueFiles:
              - values.yaml
              - '$homelab/values/cluster-issuer/{{name}}.yaml'
          repoURL: https://charts.bhyoo.com
          targetRevision: 0.3.1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
