apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      destination:
        name: '{{name}}'
        namespace: cert-manager
      project: cert-manager
      source:
        chart: cert-manager
        helm:
          releaseName: cert-manager
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/cert-manager/{{name}}.yaml'
        repoURL: https://charts.jetstack.io
        targetRevision: v1.13.1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-issuer-acme
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager-cluster-issuer'
    spec:
      destination:
        name: '{{name}}'
        namespace: cert-manager
      project: cert-manager
      source:
        chart: cluster-issuer
        helm:
          releaseName: cluster-issuer
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/cluster-issuer/{{name}}.yaml'
        repoURL: https://charts.bhyoo.com
        targetRevision: 0.3.0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
