apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-cluster-issuer
spec:
  generators:
    - list:
        elements:
          - cluster: backbone
          - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-cert-manager-cluster-issuer'
    spec:
      destination:
        name: '{{cluster}}'
        namespace: cert-manager
      project: cert-manager
      source:
        chart: cluster-issuer
        helm:
          releaseName: cert-manager-cluster-issuer
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/cluster-issuer/{{cluster}}.yaml'
        repoURL: https://isac322.github.io/homelab
        targetRevision: 0.1.0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true