apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-external-secrets'
    spec:
      destination:
        name: '{{name}}'
        namespace: kube-system
      project: secret-manager
      source:
        chart: external-secrets
        helm:
          releaseName: external-secrets
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/external-secrets/{{name}}.yaml'
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.9.8
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-secrets
spec:
  generators:
    - list:
        elements:
          - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-cluster-secrets'
    spec:
      destination:
        name: '{{cluster}}'
        namespace: kube-system
      project: secret-manager
      source:
        chart: cluster-secrets
        helm:
          releaseName: cluster-secrets
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/cluster-secrets/{{cluster}}.yaml'
        repoURL: https://charts.bhyoo.com
        targetRevision: 0.3.1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
