apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-external-secrets'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        name: '{{name}}'
        namespace: kube-system
      project: secret-manager
      sources:
        - repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          ref: homelab
        - chart: external-secrets
          helm:
            releaseName: external-secrets
            valueFiles:
              - values.yaml
              - '$homelab/values/external-secrets/{{name}}.yaml'
          repoURL: https://charts.external-secrets.io
          targetRevision: 2.3.0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-secrets
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cluster-secrets'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        name: '{{name}}'
        namespace: kube-system
      project: secret-manager
      sources:
        - repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          ref: homelab
        - chart: cluster-secrets
          helm:
            releaseName: cluster-secrets
            valueFiles:
              - values.yaml
              - '$homelab/values/cluster-secrets/{{name}}.yaml'
          repoURL: https://charts.bhyoo.com
          targetRevision: 0.3.2
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
