apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: backbone
          - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-external-dns'
    spec:
      destination:
        name: '{{cluster}}'
        namespace: dns-manager
      project: dns-manager
      source:
        chart: external-dns
        helm:
          releaseName: external-dns
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/external-dns/{{cluster}}.yaml'
        repoURL: https://isac322.github.io/homelab
        targetRevision: 0.1.2
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true