apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - list:
        elements:
          - cluster: backbone
          - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-external-secrets'
    spec:
      destination:
        name: '{{cluster}}'
        namespace: kube-system
      project: secret-manager
      source:
        chart: external-secrets
        helm:
          releaseName: external-secrets
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/external-secrets/{{cluster}}.yaml'
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.5.9
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true