apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-external-secrets'
    spec:
      destination:
        name: '{{name}}'
        namespace: kube-system
      project: secret-manager
      source:
        chart: external-secrets
        helm:
          releaseName: external-secrets
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/external-secrets/{{name}}.yaml'
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.20.4
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
        - kind: Certificate
          group: cert-manager.io
          jsonPointers:
            - /spec/duration
            - /spec/renewBefore
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-secrets
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cluster-secrets'
    spec:
      destination:
        name: '{{name}}'
        namespace: kube-system
      project: secret-manager
      source:
        chart: cluster-secrets
        helm:
          releaseName: cluster-secrets
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/cluster-secrets/{{name}}.yaml'
        repoURL: https://charts.bhyoo.com
        targetRevision: 0.3.2
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
