apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-external-dns'
    spec:
      destination:
        name: '{{name}}'
        namespace: dns-manager
      project: dns-manager
      source:
        chart: external-dns
        helm:
          releaseName: external-dns
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/external-dns/{{name}}.yaml'
        repoURL: https://kubernetes-sigs.github.io/external-dns/
        targetRevision: 1.13.1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns-cf-api-token
spec:
  generators:
    - list:
        elements:
          - cluster: backbone
            awsPath: backbone
          - cluster: prod
            awsPath: vultr
  template:
    metadata:
      name: '{{cluster}}-external-dns-cf-api-token'
    spec:
      destination:
        name: '{{cluster}}'
        namespace: dns-manager
      project: dns-manager
      source:
        path: apps/objects/external-dns
        repoURL: https://github.com/isac322/homelab.git
        targetRevision: HEAD
        kustomize:
          patches:
            - target:
                kind: ExternalSecret
                name: cloudflare-api-token
                version: external-secrets.io/v1beta1
              patch: |-
                - op: replace
                  path: /spec/data/0/remoteRef/key
                  value: /homelab/cluster/{{awsPath}}/token/cloudflare/external-dns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
        syncOptions:
          - CreateNamespace=true
