apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k3s-upgrade
spec:
  generators:
    - list:
        elements:
          - cluster: backbone
          - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-k3s-upgrade'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        name: '{{cluster}}'
        namespace: system-upgrade
      project: system-upgrade
      sources:
        - repoURL: https://github.com/rancher/system-upgrade-controller.git
          targetRevision: v0.19.0
          path: .
          kustomize:
            patches:
              - target:
                  kind: Deployment
                  name: system-upgrade-controller
                patch: |
                  - op: add
                    path: /spec/template/spec/containers/0/resources
                    value:
                      requests:
                        cpu: 5m
                        memory: 32Mi
                      limits:
                        memory: 256Mi
        - repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          path: apps/objects/k3s-system-upgrade
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: -1
        syncOptions:
          - CreateNamespace=true