apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
spec:
  generators:
    - list:
        elements:
          - cluster: backbone
          - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-traefik'
    spec:
      destination:
        name: '{{cluster}}'
        namespace: ingress-ctrl
      project: ingress-controller
      source:
        chart: traefik
        helm:
          releaseName: traefik
          valueFiles:
            - values.yaml
            - 'https://raw.githubusercontent.com/isac322/homelab/HEAD/values/traefik/{{cluster}}.yaml'
        repoURL: https://helm.traefik.io/traefik
        targetRevision: 35.2.0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: -1
        syncOptions:
          - CreateNamespace=true