ansible_host: 192.168.219.3
ansible_user: root
ansible_password: odroid
desired_ip: 192.168.219.3
gateway_ip: 192.168.219.1

is_k8s_master: false
k8s_node_labels:
  - "homelab.bhyoo.com/gpu=mali"
  - "homelab.bhyoo.com/cilium-envoy=true"

wireguard_ip: "10.222.0.1"

allow_ssh_root_login: true

emmc_io_scheduler: true

disable_services:
  - ModemManager.service
