apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: argocd-github-webhook-secret
spec:
  length: 40
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook-secret
spec:
  refreshInterval: "0"
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        webhook.github.secret: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: argocd-github-webhook-secret
      rewrite:
        - regexp:
            source: ".*"
            target: password
