{{- with .Values.wgConfig.serverKey }}
{{- if and .enabled .externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "wireguard-ui.fullname" . }}
  labels:
    {{- include "wireguard-ui.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .externalSecrets.refreshInterval | quote }}
  target:
    name: {{ include "wireguard-ui.fullname" . }}-server-private-key
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - remoteRef:
        key: {{ required "A valid .Values.wgConfig.serverKey.externalSecrets.remoteRef.key entry required!" .externalSecrets.remoteRef.key | quote }}
      secretKey: private-key
  secretStoreRef:
    name: {{ required "A valid .Values.wgConfig.serverKey.externalSecrets.secretStoreRef.name entry required!" .externalSecrets.secretStoreRef.name | quote }}
    kind: {{ required "A valid .Values.wgConfig.serverKey.externalSecrets.secretStoreRef.kind entry required!" .externalSecrets.secretStoreRef.kind }}
{{- end }}
{{- end }}