clusterSecretStore:
  aws:
    region: ap-northeast-2
    auth:
      secretRef:
        accessKeyIDSecretRef:
          key: id
          name: external-secrets-cluster-store-aws
          namespace: kube-system
        secretAccessKeySecretRef:
          key: secret
          name: external-secrets-cluster-store-aws
          namespace: kube-system

clusterExternalSecret:
  cloudflareOriginCAKey:
    externalKeyName: /homelab/shared/cloudflare/token/origin-ca
