apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: versitygw-ui
  namespace: object-storage
spec:
  parentRefs:
    - name: bhyoo-gateway
      namespace: ingress-ctrl
  hostnames:
    - versitygw.bhyoo.com
  rules:
    - backendRefs:
        - name: versitygw
          port: 8080   # webui
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: versitygw-s3
  namespace: object-storage
spec:
  parentRefs:
    - name: bhyoo-gateway
      namespace: ingress-ctrl
  hostnames:
    - s3.bhyoo.com
  rules:
    - backendRefs:
        - name: versitygw
          port: 7070   # s3-api
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: versitygw-admin
  namespace: object-storage
spec:
  parentRefs:
    - name: bhyoo-gateway
      namespace: ingress-ctrl
  hostnames:
    - admin-s3.bhyoo.com
  rules:
    - backendRefs:
        - name: versitygw
          port: 7071   # admin
