- hosts: prod
  name: Edits the hosts file in /etc
  become: yes
  roles:
    - role: etc_hosts
      vars:
        etc_hosts_ipv6: true

- hosts: homelab
  name: Edits the hosts file in /etc
  become: yes
  roles:
    - role: etc_hosts
      vars:
        etc_hosts_ipv6: false
        hosts_dns_hostname: >-
          {{
            dict(
              groups['backbone'] | map('extract', hostvars)
              | selectattr('is_k8s_master', 'defined')
              | selectattr('is_k8s_master')
              | map(attribute='ansible_host')
              | zip_longest([], fillvalue=k8s_registration_address)
            ) | dict2items(key_name='address', value_name='hostname')
          }}
