---
- hosts: backbone
  become: yes
  roles:
    - role: robertdebock.sysctl
      sysctl_items:
        - name: net.ipv4.ip_forward
          value: 1
    - role: iptables-firewall
      vars:
        k8s_role: "{{ 'master' if is_k8s_master else 'worker' }}"
        use_k3s_ha_embedded_etcd: true
        iptables_reset_all: false

- hosts: prod
  become: yes
  roles:
    - role: iptables-firewall
      vars:
        k8s_role: "{{ 'master' if is_k8s_master else 'worker' }}"
        k8s_internal_node_ip_cidr: 10.34.112.0/20
        iptables_reset_all: false
