---
- hosts: ansible_managed
  tasks:
    - ansible.builtin.include_vars: "admin_user_info.yaml"

- hosts: ansible_managed
  become: yes
  gather_facts: yes
  roles:
    - role: robertdebock.locale
      when: ansible_facts['os_family'] != "Archlinux"
    - role: locale-archlinux
      when: ansible_facts['os_family'] == "Archlinux"

- hosts: ansible_managed
  vars:
    systemd_networkd_network:
      "{{ default_iface }}":
        - Match:
            - Name: "{{ default_iface }}"
        - Network:
            - DHCP: "no"
            - MulticastDNS: "yes"
            - LLMNR: "no"
            - Address: "{{ desired_ip }}/24"
        - Route:
            - Destination: "0.0.0.0/0"
            - Gateway: "{{ gateway_ip }}"
            - GatewayOnlink: "true"
  roles:
    - role: stackhpc.systemd_networkd

- hosts: ansible_managed
  become: yes
  roles:
    - role: init-os
      vars:
        is_k8s_member: "{{ inventory_hostname in groups['backbone'] }}"