- name: Load public ips
  import_playbook: load-public-ips.yaml

- hosts: prod
  tasks:
    - name: Install k3s
      block:
        - ansible.builtin.set_fact:
            k3s_release_version: stable
            k3s_become: yes
            k3s_state: installed
            k3s_control_node: "{{ is_k8s_master }}"
            k3s_server:
              flannel-backend: 'vxlan'
              disable:
                - traefik
                - local-storage
                - metrics-server
              node-ip: "{{ private_ip }}"
              advertise-address: "{{ private_ip }}"
              node-external-ip: "{{ public_ip }}"
              kubelet-arg:
                - "image-gc-high-threshold=85"
                - "image-gc-low-threshold=80"
              tls-san:
                - "{{ inventory_hostname }}"
        - ansible.builtin.import_role:
            name: xanmanning.k3s

    - name: Create and download kubeconfig
      block:
        - ansible.builtin.set_fact:
            kubeconfig_path: /etc/rancher/k3s/k3s.yaml
            api_server_host: k8s.homelab.bhyoo.com:6443
            cluster_name: "homelab-prod"
            local_directory: _kubeconfig
            cluster_admins:
              - bhyoo-phone
              - bhyoo-desktop
            namespaced_admins:
              daily-receipt:
                - woo
          when: is_k8s_master

        - ansible.builtin.include_role:
            name: kubeconfig
            apply:
              become: yes
          when: is_k8s_master

- hosts: backbone
  tasks:
    - name: Install k3s
      block:
        - ansible.builtin.set_fact:
            k3s_release_version: stable
            k3s_become: yes
            k3s_state: installed
            k3s_control_node: "{{ is_k8s_master }}"
            k3s_server:
              flannel-backend: 'host-gw'  # This needs to be in quotes
              disable:
                - traefik
                - local-storage
              advertise-address: "{{ desired_ip }}"
              node-external-ip: "{{ wireguard_ip }}"
              kubelet-arg:
                - "image-gc-high-threshold=85"
                - "image-gc-low-threshold=80"
              node-label: "{{ k8s_node_labels }}"
            k3s_agent:
              node-external-ip: "{{ wireguard_ip }}"
              kubelet-arg:
                - "image-gc-high-threshold=85"
                - "image-gc-low-threshold=80"
              node-label: "{{ k8s_node_labels }}"
        - ansible.builtin.import_role:
            name: xanmanning.k3s

    - name: Create and download kubeconfig
      block:
        - ansible.builtin.set_fact:
            kubeconfig_path: /etc/rancher/k3s/k3s.yaml
            api_server_host: "{{ wireguard_ip }}:6443"
            cluster_name: "homelab-backbone"
            local_directory: _kubeconfig
            cluster_admins:
              - bhyoo-phone
              - bhyoo-desktop
          when: is_k8s_master

        - ansible.builtin.include_role:
            name: kubeconfig
            apply:
              become: yes
          when: is_k8s_master
