- hosts: prod
  tasks:
    - name: Install k3s
      block:
        - ansible.builtin.set_fact:
            k3s_release_version: stable
            k3s_become: yes
            k3s_state: installed
            k3s_control_node: "{{ is_k8s_master }}"
            # https://github.com/rancher/system-upgrade-controller/issues/90#issuecomment-663850596
            k3s_install_hard_links: true
#            k3s_etcd_datastore: true
            k3s_server:
              flannel-backend: 'host-gw'  # This needs to be in quotes
              disable-helm-controller: true
              disable:
#                - servicelb
                - traefik
                - local-storage
#                - metrics-server
              node-ip: "{{ main_private_ip }}"
              advertise-address: "{{ main_private_ip }}"
              node-external-ip:
                - "{{ main_public_ip }}"
                - "{{ wireguard_ip }}"
              kubelet-arg:
                - "image-gc-high-threshold=60"
                - "image-gc-low-threshold=40"
                - "feature-gates=NodeSwap=true,CloudDualStackNodeIPs=true"
              node-label: "{{ k8s_node_labels }}"
              tls-san:
                - k8s.homelab.bhyoo.com
              secrets-encryption: true
        - ansible.builtin.import_role:
            name: xanmanning.k3s

    - name: Create and download kubeconfig
      block:
        - ansible.builtin.set_fact:
            kubeconfig_path: /etc/rancher/k3s/k3s.yaml
            api_server_host: k8s.homelab.bhyoo.com:6443
            cluster_name: "homelab-prod"
            local_directory: _kubeconfig
            local_kubeconfig_prefix: prod-
            cluster_admins:
              - bhyoo-phone
              - bhyoo-tablet
              - bhyoo-desktop
              - bhyoo-office
              - bhyoo-laptop
          when: is_k8s_master

        - ansible.builtin.include_role:
            name: kubeconfig
            apply:
              become: yes
          when: is_k8s_master

- hosts: backbone
  tasks:
    - name: Install k3s
      block:
        - ansible.builtin.set_fact:
            k3s_release_version: stable
            k3s_become: yes
            k3s_state: installed
            k3s_control_node: "{{ is_k8s_master }}"
            # https://github.com/rancher/system-upgrade-controller/issues/90#issuecomment-663850596
            k3s_install_hard_links: true
            k3s_etcd_datastore: true
            k3s_registration_address: "{{ k8s_registration_address }}"
            k3s_server:
              etcd-expose-metrics: true
              flannel-backend: 'host-gw'  # This needs to be in quotes
              disable-helm-controller: true
              disable:
                - traefik
                - servicelb
              advertise-address: "{{ desired_ip }}"
              node-external-ip: "{{ wireguard_ip }}"
              kubelet-arg:
                - "image-gc-high-threshold=60"
                - "image-gc-low-threshold=40"
                - "feature-gates=NodeSwap=true,CloudDualStackNodeIPs=true"
              node-label: "{{ k8s_node_labels }}"
              secrets-encryption: true
              tls-san:
                - "{{ wireguard_ip }}"
                - "{{ wireguard_external_host }}"
                - "{{ k8s_registration_address }}"
            k3s_agent:
              node-external-ip: "{{ wireguard_ip }}"
              kubelet-arg:
                - "image-gc-high-threshold=60"
                - "image-gc-low-threshold=40"
                - "feature-gates=NodeSwap=true,CloudDualStackNodeIPs=true"
              node-label: "{{ k8s_node_labels }}"
        - ansible.builtin.import_role:
            name: xanmanning.k3s

    - name: Create and download kubeconfig
      block:
        - ansible.builtin.set_fact:
            kubeconfig_path: /etc/rancher/k3s/k3s.yaml
            api_server_host: "{{ k8s_registration_address }}:6443"
            cluster_name: "homelab-backbone"
            local_directory: _kubeconfig
            local_kubeconfig_prefix: backbone-
            cluster_admins:
              - bhyoo-phone
              - bhyoo-tablet
              - bhyoo-desktop
              - bhyoo-office
              - bhyoo-laptop
          when: is_k8s_master

        - ansible.builtin.include_role:
            name: kubeconfig
            apply:
              become: yes
          when: is_k8s_master
