---
- name: Load & register public ips
  hosts: prod
  tasks:
    - name: Load
      run_once: yes
      ansible.builtin.include_vars:
        file: /tmp/public_ip_map.yaml
        name: prod_public_ip_map
    - name: Register
      ansible.builtin.set_fact:
        public_ip: "{{ prod_public_ip_map[inventory_hostname] }}"
    - debug:
        msg: "{{public_ip}}"