collections:
  - name: devsec.hardening
    version: 10.4.0
  - name: kubernetes.core
    version: 6.2.0
  - name: cloud.terraform
    version: 4.0.0
  - name: ansible.utils
    version: 6.0.0
roles:
  - name: GROG.authorized-key
    version: v1.1.5
  - name: robertdebock.locale
    version: 3.3.11
  - name: stackhpc.systemd_networkd
    version: v1.0.6
  - name: robertdebock.sysctl
    version: 2.1.10
  - name: xanmanning.k3s
    version: v3.6.1
  - name: gantsign.helm
    version: 2.13.0
