collections:
  - name: devsec.hardening
    version: 8.2.0
  - name: kubernetes.core
    version: 2.3.2
roles:
  - name: GROG.authorized-key
    version: v1.1.5
  - name: robertdebock.locale
    version: 3.3.4
  - name: stackhpc.systemd_networkd
    version: v1.0.1
  - name: robertdebock.sysctl
    version: 2.1.3
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.0
  - name: gantsign.helm
    version: 2.10.2
