collections:
  - name: devsec.hardening
    version: 8.4.0
  - name: kubernetes.core
    version: 2.3.2
roles:
  - name: GROG.authorized-key
    version: v1.1.5
  - name: robertdebock.locale
    version: 3.3.5
  - name: stackhpc.systemd_networkd
    version: v1.0.1
  - name: robertdebock.sysctl
    version: 2.1.4
  - name: xanmanning.k3s
    version: v3.3.1
  - name: gantsign.helm
    version: 2.11.2
