collections:
  - name: devsec.hardening
    version: 8.8.0
  - name: kubernetes.core
    version: 2.4.0
  - name: cloud.terraform
    version: 2.0.0
roles:
  - name: GROG.authorized-key
    version: v1.1.5
  - name: robertdebock.locale
    version: 3.3.7
  - name: stackhpc.systemd_networkd
    version: v1.0.1
  - name: robertdebock.sysctl
    version: 2.1.6
  - name: xanmanning.k3s
    version: v3.4.3
  - name: gantsign.helm
    version: 2.13.0
