- hosts: all
  name: Setup wireguard mesh
  become: yes
  roles:
    - role: wireguard_mesh
      vars:
        cidr_block: "{{ wireguard_network }}"
        local_directory: _wireguard
        wireguard_port: 51902
        wireguard_ip_address: "{{ wireguard_ip }}"  # host specific
        wireguard_host: "{{ wireguard_external_host|default(inventory_hostname) }}"
        wireguard_internal_host: "{{ inventory_hostname }}"
        mesh_group_config:
          backbone:
            cidr: 10.222.0.0/26
            ansible_groups: ['backbone']
            gateway_host: 'rpi5'
          prod:
            cidr: 10.222.0.64/26
            ansible_groups: ['prod']
        edges:
          bhyoo-phone:
            ip_address: 10.222.0.129
            allowed_groups:
              - prod
              - backbone
          bhyoo-desktop:
            ip_address: 10.222.0.130
            allowed_groups:
              - prod
              - backbone
          bhyoo-laptop:
            ip_address: 10.222.0.131
            allowed_groups:
              - prod
              - backbone
          bhyoo-tablet:
            ip_address: 10.222.0.132
            allowed_groups:
              - prod
              - backbone
          bhyoo-office:
            ip_address: 10.222.0.133
            allowed_groups:
              - prod
              - backbone
          jay-phone:
            ip_address: 10.222.0.193
            allowed_groups:
              - backbone
          jay-tablet:
            ip_address: 10.222.0.194
            allowed_groups:
              - backbone
          jay-desktop:
            ip_address: 10.222.0.195
            allowed_groups:
              - backbone
          yjyoo-phone:
            ip_address: 10.222.0.225
            allowed_groups:
              - backbone
          gyhan-phone:
            ip_address: 10.222.0.226
            allowed_groups:
              - backbone
          gyhan-tablet:
            ip_address: 10.222.0.227
            allowed_groups:
              - backbone
