apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ca-api-key
spec:
  refreshInterval: 1h
  target:
    name: cloudflare-ca-api-key
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - remoteRef:
        key: k8s_cloudflare_ca_api_key
      secretKey: cloudflare_origin_ca_key
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore