apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cloudflare-origin-issuer
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: cloudflare-origin-ca-api-key
      key: token
