apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-tsdb
spec:
  generateBucketName: mimir-tsdb
  storageClassName: ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-ruler
spec:
  generateBucketName: mimir-ruler
  storageClassName: ceph-bucket
