default_iface: eth0
locale_lang: ko_KR.UTF-8
locale_timezone: Asia/Seoul

wireguard_port: "51902"
wireguard_interface_restart: true

wireguard_address: "{{ vpn_ip }}/32"
wireguard_endpoint: "{{ desired_ip }}"

k3s_agent:
  node-external-ip: "{{ vpn_ip }}"

authorized_key_list_group:
  - name: root
    authorized_keys:
      - key: "{{ lookup('file', './ssh_pub_keys/desktop.pub') }}"
      - key: "{{ lookup('file', './ssh_pub_keys/laptop.pub') }}"
      - key: "{{ lookup('file', './ssh_pub_keys/mobile.pub') }}"
      - key: "{{ lookup('file', './ssh_pub_keys/office.pub') }}"
  - name: "{{ admin_user }}"
    authorized_keys:
      - key: "{{ lookup('file', './ssh_pub_keys/desktop.pub') }}"
      - key: "{{ lookup('file', './ssh_pub_keys/laptop.pub') }}"
      - key: "{{ lookup('file', './ssh_pub_keys/mobile.pub') }}"
      - key: "{{ lookup('file', './ssh_pub_keys/office.pub') }}"