---
- name: Gather instance facts
  ansible.builtin.setup:

- ansible.builtin.include_tasks:
    file: verify-vars.yml

- ansible.builtin.include_tasks:
    file: interpret-configs.yml

- name: Include tasks depending on OS
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags:
        - wg-install
  with_first_found:
    - "setup-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "setup-{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
    - "setup-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml"
    - "setup-{{ ansible_distribution | lower }}.yml"
    - "setup-{{ ansible_os_family | lower }}.yml"
  tags:
    - wg-install

- name: Creates wireguard directory
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: 0750
    owner: root
    group: systemd-network

- ansible.builtin.include_tasks:
    file: generate-keys.yml
  when: _wireguard.enabled

- ansible.builtin.include_tasks:
    file: render-systemd-networkd-config.yml
  when: _wireguard.enabled

- ansible.builtin.include_tasks:
    file: render-edge-configs.yml
  when: _wireguard.enabled
