---
- name: Gather instance facts
  ansible.builtin.setup:

- ansible.builtin.include_tasks:
    file: verify-vars.yml

- ansible.builtin.include_tasks:
    file: interpret-configs.yml

- name: Creates wireguard directory
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: 0750
    owner: root
    group: systemd-network

- ansible.builtin.include_tasks:
    file: generate-keys.yml
  when: _wireguard.enabled

- ansible.builtin.include_tasks:
    file: render-systemd-networkd-config.yml
  when: _wireguard.enabled

- ansible.builtin.include_tasks:
    file: render-edge-configs.yml
  when: _wireguard.enabled
