apiVersion: objectstorage.k8s.io/v1alpha1
kind: Bucket
metadata:
  name: cnpg-immich-backup-hdd
spec:
  bucketClaim:
    name: cnpg-immich-backup-hdd
    namespace: immich
  bucketClassName: versitygw-hdd-cosi-driver
  driverName: versitygw-hdd.cosi.dev
  deletionPolicy: Retain
  protocols:
    - S3
