apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-smtp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: immich-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        immich-config.yaml: |
          job:
            ocr:
              concurrency: 3
            smartSearch:
              concurrency: 4
            videoConversion:
              concurrency: 6
            thumbnailGeneration:
              concurrency: 5
          image:
            preview:
              format: webp
          ffmpeg:
            accel: rkmpp
            preset: slower
            tonemap: reinhard
            twoPass: true
            realtime:
              enabled: true
              resolutions:
                - 480
                - 720
                - 1080
                - 1440
                - 2160
            transcode: bitrate
            maxBitrate: 2600k
            targetVideoCodec: hevc
            acceptedVideoCodecs:
              - hevc
              - vp9
              - h264
              - av1
          server:
            externalDomain: https://immich.bhyoo.com
          library:
            watch:
              enabled: true
          metadata:
            faces:
              import: true
          machineLearning:
            ocr:
              modelName: KOREAN__PP-OCRv5_mobile
            clip:
              modelName: nllb-clip-large-siglip__mrl
          notifications:
            smtp:
              enabled: true
              from: Immich <bhyoo@bhyoo.com>
              replyTo: bhyoo@bhyoo.com
              transport:
                ignoreCert: false
                host: smtp.postmarkapp.com
                port: 587
                secure: false
                username: "{{ .smtpToken }}"
                password: "{{ .smtpToken }}"
  data:
    - secretKey: smtpToken
      remoteRef:
        key: /homelab/cluster/backbone/token/postmark/immich-smtp
