apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-smtp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: immich-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        immich-config.yaml: |
          notifications:
            smtp:
              enabled: true
              from: Immich <bhyoo@bhyoo.com>
              replyTo: bhyoo@bhyoo.com
              transport:
                ignoreCert: false
                host: smtp.postmarkapp.com
                port: 587
                secure: false
                username: "{{ .smtpToken }}"
                password: "{{ .smtpToken }}"
  data:
    - secretKey: smtpToken
      remoteRef:
        key: /homelab/cluster/backbone/token/postmark/immich-smtp
