apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning-heterogeneous
spec:
  ports:
  - name: http
    port: 3003
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: machine-learning
  type: ClusterIP
