apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: immich-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 768Gi
  storageClassName: hdd-ha-local
