apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  name: cnpg-hindsight-backup
spec:
  bucketClassName: versitygw
  existingBucketName: cnpg-hindsight-backup
  protocols:
    - S3
