apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight-s3-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes
    kind: SecretStore
  target:
    name: hindsight-s3-creds
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ (.BucketInfo | fromJson).spec.secretS3.accessKeyID }}"
        ACCESS_SECRET_KEY: "{{ (.BucketInfo | fromJson).spec.secretS3.accessSecretKey }}"
  data:
    - secretKey: BucketInfo
      remoteRef:
        key: cnpg-hindsight-backup-creds
        property: BucketInfo
