apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hindsight-model-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-ha-xfs
  resources:
    requests:
      storage: 5Gi
