certificate:
  # -- Certificate primary domain (commonName)
  domain: argocd.bhyoo.com
  # -- The name of the Secret that will be automatically created and managed by this Certificate resource
  secretName: argocd-server-cert
  email: "bh322yoo@gmail.com"
  organizations:
    - ByeonghoonYoo

cloudflareOriginIssuer:
  apiToken: AgBY5Za8bFeOHTswGauEg5JG7LWEWgRBVhgt6/CAP2lYnl7UHFk6b/xdalAPK/7EA5rxuJ6Z9ogug90ugmGDqJ2sCyOvJ3wgDpZbmuqSAVpxZ5u6OWQfHiV0Xf9XyrYQnpJ0sOK6sr6XRrZtkivT3NBnuf59u7C1bH1aFzmflrRwTFugI2hxM/oNensPjudO3g0DiuPpEGHiqe4sPXYD3l9+ck3IlwywIeQftiQ54MCpCg0HQTtUdHubFPnuwqPC8V01s4MpCrdp2hHH5qSKjPTHfyzN6y/0AWXKRejv0OTzRcCEugUasTuoRjPaxSwF3z1vi62S0j2pzWSPP+Sb9e/NgyuBOvOTNB/XrpGjWGaVp7SNXUFXm6CeVrhmQN7RYEiBtliXV51MhXDSoIznmdJsiriIFwM6rPooczo1Sh9xKNZJccjb3eOlTrvQzdbXHw+WvWWVRdV/QokRCBs7jKHb1dRjF41wUnvVuzN3fqUb4O4gXJTOAP4o67xULK+PJHiKBz+OZf574OsBE2xNYcRgzRKpVPGlO3gwBr+lQwz1H66bT0NWrTT/Zrp5+Tg3707YqMu6mcH6hQHatdYIp26xiXXa4XND7S/+NHPEKhKB8kc1e5ZT0ocZN4bB4uK7aQto2OxAFOwUjYbJqNjsNDz4CAkQ2DCdFr/tqgPA/E4NTWuz4uenNOuGsDH82YmoXNcNKkdj/9vSSO8DjBQUb/caKgsqmx7TcPH8+TjwsWdwX/WHZZjS2S3/mmqTT6ADV9bb+NhV/e8v2r8I8y6u4pj/EekXle8wyTh9gKNpJjFqNHVQ7dU7qKpTrl31wLtLfH4uV7TkAnJDkJ4Dn2UmNE93uGB5aKCEayVw7Pe3olRd+iZWv6dX3FXs09cqOEykAbRekDqQ/eEzsxuTxMy9qg+cvwq/R1xuWOPoSZSDBAk=

parent:
  # FIXME: remove this after https://github.com/argoproj/argo-cd/issues/8394 merges
  applicationSet:
    image:
      repository: ghcr.io/jr64/argocd-applicationset
      tag: v0.4.0


  server:
    config:
      repositories: |
        - type: git
          url: https://github.com/isac322/homelab.git
        - name: homelab
          type: helm
          url: https://isac322.github.io/homelab/
        - name: traefik
          type: helm
          url: https://helm.traefik.io/traefik
        - name: cert-manager
          type: helm
          url: https://charts.jetstack.io
        - name: sealed-secrets
          type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
        - name: cloudflare-origin-ca-issuer
          type: helm
          url: https://cloudflare.github.io/origin-ca-issuer/charts
        - type: git
          url: https://github.com/cloudflare/origin-ca-issuer.git

    additionalApplications:
      - name: argocd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          chart: argocd
          helm:
            valueFiles:
              - values.yaml
              - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/argocd/backbone.yml
          repoURL: https://isac322.github.io/homelab
          targetRevision: 0.1.3
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          retry:
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m0s
            limit: 2
          syncOptions:
            - CreateNamespace=true
        ignoreDifferences:
          - kind: Certificate
            group: cert-manager.io
            jsonPointers:
              - /spec/duration
              - /spec/renewBefore
      - name: argocd-apps
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: argocd/backbone/apps
          repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          directory:
            recurse: true
            jsonnet: { }
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          retry:
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m0s
            limit: 2
      - name: argocd-appprojects
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: argocd/backbone/appprojects
          repoURL: https://github.com/isac322/homelab.git
          targetRevision: HEAD
          directory:
            recurse: true
            jsonnet: { }
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          retry:
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m0s
            limit: 2

    additionalProjects:
      - name: argocd
        namespace: argocd
        description: Argocd Project
        sourceRepos:
          - '*'
        destinations:
          - namespace: argocd
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
        orphanedResources:
          warn: false

    extraArgs:
      - --insecure

    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: true
      # -- Additional ingress annotations
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure

      # -- Defines which ingress controller will implement the resource
      ingressClassName: traefik

      # -- List of ingress hosts
      ## Argo Ingress.
      ## Hostnames must be provided if Ingress is enabled.
      ## Secrets must be manually created in the namespace
      hosts:
        - argocd.bhyoo.com

      # -- Ingress TLS configuration
      tls:
        - hosts:
            - argocd.bhyoo.com
          secretName: argocd-server-cert

      # -- Uses `server.service.servicePortHttps` instead `server.service.servicePortHttp`
      https: false
