---
apiVersion: v1
data:
  ca.crt: '-----BEGIN CERTIFICATE-----

    MIIGDjCCA/agAwIBAgIUL6N+XLXDixGRO7fDfgYpNGWr/54wDQYJKoZIhvcNAQEL

    BQAwgZ4xCzAJBgNVBAYTAk5MMRYwFAYDVQQIDA1Ob29yZCBIb2xsYW5kMRIwEAYD

    VQQHDAlBbXN0ZXJkYW0xCzAJBgNVBAoMAk1FMQswCQYDVQQLDAJJVDFJMEcGA1UE

    AwxARG9ja2VyTWlycm9yQm94IENBIFJvb3QgZG9ja2VyLXJlZ2lzdHJ5LXByb3h5

    LTY4Y2ZiNTViNWItbGJyOXAgMjAeFw0yNjA1MjkwNzA1MzZaFw0yOTEyMTkwNzA1

    MzZaMIGeMQswCQYDVQQGEwJOTDEWMBQGA1UECAwNTm9vcmQgSG9sbGFuZDESMBAG

    A1UEBwwJQW1zdGVyZGFtMQswCQYDVQQKDAJNRTELMAkGA1UECwwCSVQxSTBHBgNV

    BAMMQERvY2tlck1pcnJvckJveCBDQSBSb290IGRvY2tlci1yZWdpc3RyeS1wcm94

    eS02OGNmYjU1YjViLWxicjlwIDIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK

    AoICAQCkoz3LMrm0W4eAFrIHnrLRhChMsC3XvURiivEe0PkdVqiS6QAgjiJ7DuyX

    1l7XEkhambVYtKIAoIvlNwKYFwrRqkYlAHCDA0/afMNqnsGpx7lXIlSefESTgizh

    8zYUFA1uF9GMKRmw32KjYgicaeJ0hWuTaVUW7PZe7c2hV5BMm5G6XzeOk9fXQN25

    pxqE3dfyxLw6ebqKab02mqEiWsKgVvzxgHA8N7C7u8eh1xlMWe/G5799ecbwZFM4

    IF8v/wUp0G3ud1QoqRO0me7MPRlIe/k+zX1pOO1sziqYivmO/EKAg0XaH9rdcKOg

    GxjBjcPvsSeT4xZseT9zmJb5tJCgo//Xy9NZfx1entBgv85xLVdCcsx1hxhGc1gc

    i2SV6x1cebm2tN9oJ3Hn5a2PNn7PAyIS8nXdLb6W6R33dvmDP73s2M9SBWWbBdbV

    ep2hXl7vaXLVgyTT8UjpxLMQ0DkQnmqDud01UAPvoR4EqG+grxFYtp8M6w1YpP5Y

    9lnd8dbZxB5HyVSX3CNPejA5UCMA4N2edY/0dDhsxbW++9cMzFslHbxXmCstuL/h

    WQTtTVO809X40ubKY6Jz5Jdp+11ghimMIjnhQnEAdA9HY2mN+dNRugGKRcXGOmRe

    4MXDNYRJ1qydxo1BSETstexB49+rrYAPNy4vElu+wO96SICIyQIDAQABo0IwQDAP

    BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQURWR6e7Oh

    AB4idEh0REmwadSKif4wDQYJKoZIhvcNAQELBQADggIBADaBPH7kqmBs6hfHjgzk

    UkgiJyH7u1XhoHoD+bMbmi+N4CbYTtRQHgEafEbvafUfs4W/0YLtO+plme7/QBC4

    CJiagtHbpO3oI/FHAFlTPm/8v0wvrJ6tbc0avkj3K1T2sBK+U8xc4+HbHxlqDD8j

    wfn3oBnRB/YrYdX2ZmvGPSLxriVjWSy/dVm4rm4QTICc4L1MbkOFpn1KBUHoqSpj

    J7KjJvOrHsJ64P75hcOj9yMbHuNTfCw48C0kR941msUu73nnxMi3STodAVaqm5Z6

    A7g2a9ru1Vo+S7KTct/beitqLdMiI2fi/SWasYvNIhEmnWzJ9tpGEF9RH0/ei6wj

    p6gw6bAgnpANKPqVLynIDDXVSU5Nxjk/S+kCwhvaUmSKIycp+Yv0R5aY9r4COSYS

    O3H3lcKnDowu3K/xNujPJUYY1OfdRgdYmAdpRQi3TN/p7hoE3HMWmernnKHTkxEU

    1dxml0MljoD9HIFeNY7c6P5aWDYEpl5yvCFQUx78iKPBh+QapZJZCO6v6hGclX51

    gRdV5fy1xbpZUOTRNygD1yZKS4Pq319mIt/YYfRRlc1u02Z+M+FOJNh6mW8PCVL1

    W989LqF5NkMAnqcIjDLmq8emdhBTYpzcjKvCim46UDcE7IXlPQovb6kVcnQLAENY

    ghJW4lj9EFpUHGAqIzpcQz2c

    -----END CERTIFICATE-----

    '
kind: ConfigMap
metadata:
  name: registry-proxy-ca
  namespace: arc-runners
