apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: versitygw-hdd-access-key
spec:
  length: 20
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: versitygw-hdd-secret-key
spec:
  length: 40
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: versitygw-hdd-root-credentials
spec:
  refreshInterval: "0"
  target:
    name: versitygw-hdd-root-credentials
    creationPolicy: Orphan
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: versitygw-hdd-access-key
      rewrite:
        - regexp:
            source: ".*"
            target: rootAccessKeyId
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: versitygw-hdd-secret-key
      rewrite:
        - regexp:
            source: ".*"
            target: rootSecretAccessKey
