apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: versitygw-hdd
  labels:
    app.kubernetes.io/instance: versitygw-hdd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: versitygw-hdd
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
