apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: arc-systems
data:
  buildkitd.toml: |
    [registry."docker.io"]
      mirrors = ["registry-docker-io.arc-systems.svc.cluster.local:5000"]

    [registry."registry-docker-io.arc-systems.svc.cluster.local:5000"]
      http = true
      insecure = true

    [registry."ghcr.io"]
      mirrors = ["registry-ghcr-io.arc-systems.svc.cluster.local:5000"]

    [registry."registry-ghcr-io.arc-systems.svc.cluster.local:5000"]
      http = true
      insecure = true
