apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: arc-systems
  labels:
    app: buildkit
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
      annotations:
        checksum/config: df4ea3370cc3fa67c0964f7ea374bf200d43d3c1f68ee6f8e8c887cbea1f75a5
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: buildkitd
          image: docker.io/moby/buildkit:v0.33.0@sha256:6c2fa84a6b61ccd72899dde4239f8d5717f05f9a8ca6f3cad185fb1a95a94de3
          args:
            - --config
            - /etc/buildkit/buildkitd.toml
          env:
            - name: GOMAXPROCS
              value: "4"
            - name: BUILDKIT_HOST
              value: unix:///run/buildkit/buildkitd.sock
          ports:
            - name: buildkit
              containerPort: 1234
            - name: debug
              containerPort: 6060
          resources:
            requests:
              cpu: "4"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          securityContext:
            privileged: true
          volumeMounts:
            - name: cache
              mountPath: /var/lib/buildkit
            - name: config
              mountPath: /etc/buildkit
              readOnly: true
          startupProbe:
            exec:
              command: ["buildctl", "debug", "workers"]
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 60
          readinessProbe:
            exec:
              command: ["buildctl", "debug", "workers"]
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["buildctl", "debug", "workers"]
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: buildkit-cache
        - name: config
          configMap:
            name: buildkitd-config
