apiVersion: v1
kind: Service
metadata:
  name: buildkit
  namespace: arc-systems
  labels:
    app: buildkit
spec:
  selector:
    app: buildkit
  ports:
    - name: buildkit
      port: 1234
      targetPort: 1234
