apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-smtp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: vaultwarden-smtp
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /homelab/cluster/backbone/token/postmark/vaultwarden-smtp
