apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: storage-canary
  labels:
    app.kubernetes.io/name: storage-canary
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storage-canary
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
