apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "get-oracle-a1.fullname" . }}
  labels:
  {{- include "get-oracle-a1.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    config: {{ .Values.ociConfig.sealedSecrets.config }}
    cert: {{ .Values.ociConfig.sealedSecrets.cert }}
    {{- range $key, $val := .Values.sealedSecret }}
    {{ $key }}: {{ $val }}
    {{- end}}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ include "get-oracle-a1.fullname" . }}
      namespace: {{ .Release.Namespace }}