apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Certificate manager
  sourceRepos:
    - https://charts.jetstack.io
    - https://isac322.github.io/homelab
    - https://cloudflare.github.io/origin-ca-issuer/charts
    - https://github.com/cloudflare/origin-ca-issuer.git
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
