apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dns-manager
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Managing external DNS
  sourceRepos:
    - https://isac322.github.io/homelab
  destinations:
    - namespace: dns-manager
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
