apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secret-manager
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Managing secret of kubernetes cluster
  sourceRepos:
    - https://bitnami-labs.github.io/sealed-secrets
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
