apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: isacmes-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: isacmes-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          external-secrets.io/type: webhook
  data:
    - secretKey: token
      remoteRef:
        key: /homelab/cluster/backbone/token/telegram/isacmes
    - secretKey: apiKey
      remoteRef:
        key: /homelab/cluster/backbone/token/openai/isacmes
    - secretKey: baseUrl
      remoteRef:
        key: /homelab/cluster/backbone/token/openai/isacmes-base-url
    - secretKey: geminiApiKey
      remoteRef:
        key: /homelab/cluster/backbone/token/google/isacmes
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: isacmes-jay-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: isacmes-jay-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /homelab/cluster/backbone/token/telegram/isacmes-jay
    - secretKey: apiKey
      remoteRef:
        key: /homelab/cluster/backbone/token/openai/isacmes-jay
    - secretKey: baseUrl
      remoteRef:
        key: /homelab/cluster/backbone/token/openai/isacmes-jay-base-url
    - secretKey: geminiApiKey
      remoteRef:
        key: /homelab/cluster/backbone/token/google/isacmes-jay
