apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "cluster-secrets.fullname" . }}
  labels:
    {{- include "cluster-secrets.labels" . | nindent 4 }}
spec:
  provider:
    {{- if .Values.clusterSecretStore.oracle.enabled }}
    oracle:
      region: {{ .Values.clusterSecretStore.oracle.region | quote }}
      vault: {{ .Values.clusterSecretStore.oracle.vaultOCID | quote }}
      auth:
        secretRef:
          fingerprint:
            name: {{ include "cluster-secrets.fullname" . }}
            namespace: {{ .Release.Namespace }}
            key: fingerprint
          privatekey:
            name: {{ include "cluster-secrets.fullname" . }}
            namespace: {{ .Release.Namespace }}
            key: privateKey
        tenancy: {{ .Values.clusterSecretStore.oracle.tenancyOCID | quote }}
        user: {{ .Values.clusterSecretStore.oracle.userOCID | quote }}
    {{- end }}
