apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "cluster-secrets.fullname" . }}
  labels:
    {{- include "cluster-secrets.labels" . | nindent 4 }}
spec:
  provider:
    {{- if .Values.clusterSecretStore.oracle.enabled }}
    oracle:
      region: {{ .Values.clusterSecretStore.oracle.region | quote }}
      vault: {{ .Values.clusterSecretStore.oracle.vaultOCID | quote }}
      auth:
        secretRef:
          {{- toYaml .Values.clusterSecretStore.aws.auth | nindent 10 }}
        tenancy: {{ .Values.clusterSecretStore.oracle.auth.tenancyOCID | quote }}
        user: {{ .Values.clusterSecretStore.oracle.auth.userOCID | quote }}
    {{- end }}
    {{- if .Values.clusterSecretStore.aws.enabled }}
    aws:
      region: {{ required "A valid .Values.clusterSecretStore.aws.region entry required!" .Values.clusterSecretStore.aws.region | quote }}
      service: {{ required "A valid .Values.clusterSecretStore.aws.service entry required!" .Values.clusterSecretStore.aws.service | quote }}
      {{- with .Values.clusterSecretStore.aws.role }}
      role: {{ . }}
      {{- end }}
      auth:
        {{- toYaml .Values.clusterSecretStore.aws.auth | nindent 8 }}
    {{- end }}
