apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ include "cluster-secret-store.fullname" . }}-{{ required "A valid .Values.clusterExternalSecret.cloudflareCAAPIKey.secretName entry required!" .Values.clusterExternalSecret.cloudflareCAAPIKey.secretName }}
  labels:
    {{- include "cluster-secret-store.labels" . | nindent 4 }}
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: {{ .Values.clusterExternalSecret.cloudflareCAAPIKey.secretName }}

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels:
      homelab/cloudflare-ca-required: "true"

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    secretStoreRef:
      name: {{ include "cluster-secret-store.fullname" . }}
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: {{ .Values.clusterExternalSecret.cloudflareCAAPIKey.secretName }}
      creationPolicy: Owner
      deletionPolicy: Delete
    data:
      - secretKey: cloudflare_origin_ca_key
        remoteRef:
          key: {{ .Values.clusterExternalSecret.cloudflareCAAPIKey.externalKeyName }}