apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "registry.fullname" . }}-config
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ toYaml .Values.configData | indent 4 }}
