apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "registry.fullname" . }}
  labels:
  {{- include "registry.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .Values.sealedSecret }}
      {{- if ne $val "" }}
      {{ $key }}: {{ $val }}
      {{- end }}
    {{- end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ include "registry.fullname" . }}
      namespace: {{ .Release.Namespace }}