apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-origin-ca-key
  namespace: default
spec:
  encryptedData:
    cloudflare_origin_ca_key: AgASUTcMBEE4RZ05PKi/4gBhBugJbd2WrHcWheQbZtrP1RvOMOAb2fHLki7t4x6hqs7KALw7WdRRtDDnRcKZaSwe+Pnx6ykT5tszATPS/L3G/P0i6P6Ayf+jQwPuFD3xfetwClccj0fu+VKwjhNDeFooKpqPT7wjN91EnzerRpr5GlVFwPb2wrNUEjZvYZFhQv+7KPpXnxI87jRsfHpcvSd6lnVc5EN7apBD97fTAXoALLT6norkI9czCwjWuIzWaPk0gGTIkqK0MGSIyEK8xznPsD9AN7vZSWhbg0rkLF1VFqUJ/q5wRLhFbUwKrPCOxosnJls4Q+UzTDAIC2zovl/DRm05od2+AHT7aML5uuBQQfuFFW+mv/MyRek22MYAHiVW+fvw9w4xDuGSHeIn4ADCXV0ipeX4CONlmgUIWuGNjpI3Oiyi4zRfaRVFR9qby7KIjXDUKo3qm2Sdd5ZU6hUcKQMZ6FYepGmePdbmuV+3ptjFEYg3zwJYsXat3f8ybGZZKqfac1TMbJNZQpasHAV/M+3E/+8MsvEYPvV96gMXpNuqOLPfPY0drr/M+1hYvC/uJVUiuJ4Yz1oMg+q3frXfDhHr0Uap1s5fdGvioWJJddhlmziKthu+nQlN42TiwISevPdkzyj5z6/tnVLsOC6ARESqJKiij+uqNXgXk5ttt2K/zDEZeEqGUtvORT95K7b77cGhKbgQGeyJI02USNB6wwUnksmjORQDNtfBcZdVUazIoMviRpxmvjXJ4rbAGdm7SSzRcik/4vviGlb0gYpegmlnwCqc8yfnuYJrmiPq80ARcfhfmenCrZXMarxhDvBI5CEjzLEgzMqEGfibRZAFPhNJmkqCDvSxm0f8UqKjCMxi5aJqcmT4J+gkS+6tPqJQcuD3UBZn7MbMZJ43BTCgCvCl1pQG5tOg/sq7YAw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cf-origin-ca-key
      namespace: default

