serviceMonitor:
  enabled: true

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: token

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 128Mi

sources:
  - service
  - ingress

policy: sync

registry: txt
txtOwnerId: k8s-vultr

domainFilters:
  - bhyoo.com

provider:
  name: cloudflare

extraArgs:
  - --service-type-filter=LoadBalancer
  - --cloudflare-proxied
