serviceMonitor:
  enabled: true

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-origin-ca-api-key
        key: token

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 100Mi

logLevel: info
logFormat: text

interval: 1m

sources:
  - service
  - ingress

policy: sync

registry: txt
txtOwnerId: k8s-vultr

domainFilters:
  - bhyoo.com

provider: cloudflare

extraArgs:
  - --service-type-filter=LoadBalancer
  - --cloudflare-proxied
