apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dolfan-crawler
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: dolfan
  project: dolfan
  source:
    chart: redis-cluster
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/dolfan/backbone.yaml
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 10.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
