apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: object-storage
  project: object-storage
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: operator
      helm:
        valueFiles:
          - values.yaml
          - $homelab/values/minio/backbone.yaml
      repoURL: https://operator.min.io/
      targetRevision: 7.1.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: object-storage
  project: object-storage
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: tenant
      helm:
        valueFiles:
          - values.yaml
          - $homelab/values/minio/tenant-shared.yaml
      repoURL: https://operator.min.io/
      targetRevision: 7.1.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
