apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-internal
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: prod
    namespace: ingress-ctrl
  project: ingress-controller
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: traefik
      helm:
        releaseName: internal
        valueFiles:
          - values.yaml
          - $homelab/values/traefik/prod-internal.yaml
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 26.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true