apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-systems
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set-controller
      helm:
        releaseName: arc
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set-controller/backbone.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller-objects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  source:
    path: apps/objects/actions-runner-controller
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cc-lb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      helm:
        releaseName: cc-lb
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set/cc-lb-light.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cc-lb-heavy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      helm:
        releaseName: cc-lb-heavy
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set/cc-lb-heavy.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
