apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-systems
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set-controller
      helm:
        releaseName: arc
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set-controller/backbone.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller-objects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  source:
    path: apps/objects/actions-runner-controller
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buildkit
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-systems
  project: github-actions-runner
  source:
    path: apps/objects/buildkit
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-mirror
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-systems
  project: github-actions-runner
  source:
    path: apps/objects/registry-mirror
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-cache-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-systems
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: github-actions-cache-server
      helm:
        releaseName: gha-cache-server
        valueFiles:
          - $homelab/values/gha-cache-server/backbone.yaml
      repoURL: ghcr.io/falcondev-oss/charts
      targetRevision: 1.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cc-lb-500m
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      helm:
        releaseName: cc-lb-500m
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set/cc-lb-500m.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cc-lb-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      helm:
        releaseName: cc-lb-1
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set/cc-lb-1.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cc-lb-2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      helm:
        releaseName: cc-lb-2
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set/cc-lb-2.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cc-lb-4
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      helm:
        releaseName: cc-lb-4
        valueFiles:
          - values.yaml
          - $homelab/values/gha-runner-scale-set/cc-lb-4.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
