apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: kube-system
  project: monitoring
  source:
    chart: alloy
    helm:
      releaseName: alloy
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/alloy/backbone.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
