apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: backbone
    namespace: argocd
  project: argocd
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: argo-cd
      helm:
        valueFiles:
          - values.yaml
          - $homelab/values/argo-cd/backbone.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 9.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: -1
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-meta
spec:
  destination:
    name: backbone
    namespace: argocd
  project: argocd
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: argocd-apps
      helm:
        valueFiles:
          - values.yaml
          - $homelab/values/argocd-apps/backbone.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.0.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: -1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-objects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: argocd
  project: argocd
  source:
    repoURL: https://github.com/isac322/homelab.git
    path: apps/objects/argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
