apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: backbone
    namespace: argocd
  project: argocd
  source:
    chart: argo-cd
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/argo-cd/backbone.yaml
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.5.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: -1
  ignoreDifferences:
    - kind: Certificate
      group: cert-manager.io
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo/argocd-apps
spec:
  destination:
    name: backbone
    namespace: argocd
  project: argocd
  source:
    chart: argo/argocd-apps
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/argocd-apps/backbone.yaml
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: -1
---