apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
spec:
  destination:
    name: prod
    namespace: blocky
  project: ad-block
  source:
    chart: blocky
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/blocky/prod.yaml
    repoURL: https://charts.bhyoo.com
    targetRevision: 0.22.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Certificate
      group: cert-manager.io
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
