apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: prod
    namespace: blocky
  project: ad-block
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: blocky
      helm:
        valueFiles:
          - values.yaml
          - $homelab/values/blocky/prod.yaml
      repoURL: https://charts.bhyoo.com
      targetRevision: 0.24.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
