# CRDs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-origin-ca-issuer-crds
spec:
  destination:
    name: prod
    namespace: origin-ca-issuer
  project: cert-manager
  source:
    path: deploy/crds
    targetRevision: v0.7.0
    repoURL: https://github.com/cloudflare/origin-ca-issuer.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-origin-ca-issuer
spec:
  destination:
    name: prod
    namespace: origin-ca-issuer
  project: cert-manager
  source:
    chart: origin-ca-issuer
    helm:
      releaseName: origin-ca-issuer
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/origin-ca-issuer/prod.yaml
    repoURL: ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer
    targetRevision: 0.5.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true