# CRDs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-origin-ca-issuer-crds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: prod
    namespace: origin-ca-issuer
  project: cert-manager
  source:
    path: deploy/crds
    targetRevision: v0.13.0
    repoURL: https://github.com/cloudflare/origin-ca-issuer.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-origin-ca-issuer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: prod
    namespace: origin-ca-issuer
  project: cert-manager
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: origin-ca-issuer
      helm:
        releaseName: origin-ca-issuer
        valueFiles:
          - values.yaml
          - $homelab/values/origin-ca-issuer/prod.yaml
      repoURL: ghcr.io/cloudflare/origin-ca-issuer-charts
      targetRevision: 0.6.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true