apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: object-storage
  project: object-storage
  source:
    repoURL: https://github.com/kubernetes-sigs/container-object-storage-interface.git
    path: .
    targetRevision: v0.2.2
    kustomize:
      namespace: object-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
