apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
spec:
  destination:
    name: backbone
    namespace: csi-driver-nfs
  project: dfs
  source:
    chart: csi-driver-nfs
    helm:
      releaseName: csi-driver-nfs
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/csi-driver-nfs/backbone.yaml
    repoURL: csi-driver-nfs
    targetRevision: v4.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
