apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-ssd-iscsi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: democratic-csi
  project: dfs
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: democratic-csi
      helm:
        releaseName: ssd-iscsi
        valueFiles:
          - values.yaml
          - $homelab/values/democratic-csi/backbone.yaml
      repoURL: https://democratic-csi.github.io/charts/
      targetRevision: 0.15.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-hdd-iscsi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: democratic-csi
  project: dfs
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: democratic-csi
      helm:
        releaseName: hdd-iscsi
        valueFiles:
          - values.yaml
          - $homelab/values/democratic-csi/hdd-backbone.yaml
      repoURL: https://democratic-csi.github.io/charts/
      targetRevision: 0.15.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
