apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler-objects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: kube-system
  project: cluster-management
  source:
    repoURL: https://github.com/isac322/homelab.git
    path: apps/objects/descheduler
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
