apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle4-actions-runner-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  destination:
    name: oracle4
    namespace: arc-systems
  project: github-actions-runner
  source:
    repoURL: https://github.com/isac322/homelab.git
    path: apps/objects/actions-runner-controller/oracle4
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle4-arc-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  destination:
    name: oracle4
    namespace: arc-systems
  project: github-actions-runner
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.14.2
    helm:
      releaseName: arc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle4-cc-lb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: oracle4
    namespace: arc-runners
  project: github-actions-runner
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: gha-runner-scale-set
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
      helm:
        releaseName: oracle4-cc-lb
        valueFiles:
          - $homelab/values/actions-runner-controller/oracle4-cc-lb.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
