apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issue-agent
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: issue-agent
  project: issue-agent
  source:
    path: apps/objects/issue-agent
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
