apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: jellyfin
  project: nas
  source:
    chart: jellyfin
    helm:
      releaseName: jellyfin
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/jellyfin/backbone.yaml
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.7.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
