apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: jellyfin
  project: nas
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: jellyfin
      helm:
        releaseName: jellyfin
        valueFiles:
          - values.yaml
          - $homelab/values/jellyfin/backbone.yaml
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 3.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
