apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: kube-system
  project: secret-manager
  source:
    chart: reflector
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/reflector/backbone.yaml
    repoURL: ghcr.io/emberstack/helm-charts
    targetRevision: 9.1.38
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
