apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: loki
  project: monitoring
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: loki
      helm:
        releaseName: loki
        valueFiles:
          - values.yaml
          - $homelab/values/loki/backbone.yaml
      repoURL: https://grafana-community.github.io/helm-charts
      targetRevision: 13.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
