apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
spec:
  destination:
    name: prod
    namespace: mimir
  project: monitoring
  source:
    chart: grafana/mimir-distributed
    helm:
      releaseName: mimir
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/mimir/prod.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-rook-rgw
spec:
  destination:
    name: prod
    namespace: mimir
  project: monitoring
  source:
    path: apps/objects/mimir-rook-rgw
    targetRevision: HEAD
    repoURL: https://github.com/isac322/homelab.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: -1
    syncOptions:
      - CreateNamespace=true
