apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: questdb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: questdb
  project: questdb
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: questdb
      helm:
        releaseName: questdb
        valueFiles:
          - values.yaml
          - $homelab/values/questdb/backbone.yaml
      repoURL: https://helm.questdb.io/
      targetRevision: 1.0.21
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
