apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-objects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: prometheus
  project: monitoring
  source:
    path: apps/objects/thanos
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
