apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: prometheus
  project: monitoring
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: thanos
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 17.3.1
      helm:
        releaseName: thanos
        valueFiles:
          - values.yaml
          - $homelab/values/thanos/backbone.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
