apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: versitygw
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: object-storage
  project: object-storage
  source:
    chart: versitygw
    repoURL: ghcr.io/versity/versitygw/charts
    targetRevision: 0.3.1
    helm:
      releaseName: versitygw
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/versitygw/backbone.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: versitygw-objects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: object-storage
  project: object-storage
  source:
    path: apps/objects/versitygw
    repoURL: https://github.com/isac322/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
