apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: versitygw-cosi-driver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: backbone
    namespace: object-storage
  project: object-storage
  sources:
    - repoURL: https://github.com/isac322/homelab.git
      targetRevision: HEAD
      ref: homelab
    - chart: versitygw-cosi-driver
      repoURL: ghcr.io/isac322/charts
      targetRevision: 0.3.6
      helm:
        releaseName: versitygw-cosi-driver
        valueFiles:
          - values.yaml
          - $homelab/values/versitygw-cosi-driver/backbone.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100
    syncOptions:
      - CreateNamespace=true
