resources:
  requests:
    cpu: 10m
    memory: 48Mi
  limits:
    cpu: 100m
    memory: 64Mi

serviceMonitor:
  enabled: true

webhook:
  serviceMonitor:
    enabled: true

  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

  certManager:
    enabled: true
    cert:
      issuerRef:
        kind: ClusterIssuer
        name: cluster-issuer-self-signed
      duration: 8760h
      renewBefore: 24h

certController:
  create: false
