apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: issue-agent-publisher
spec:
  length: 64
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: issue-agent-publisher
spec:
  refreshInterval: "0"
  target:
    name: issue-agent-publisher
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: issue-agent-publisher
      rewrite:
        - regexp:
            source: ".*"
            target: password
