clusterSecretStore:
  oracle:
    enabled: false
    region: ""
    vaultOCID: ""
    auth:
      secretRef: {}
        # key: ""
        # name: ""
        # namespace: ""
      tenancyOCID: ""
      userOCID: ""
  aws:
    enabled: true
    region: ""
    service: ParameterStore # or SecretsManager
    role: ""
    auth: {}
      # secretRef:
      #   accessKeyIDSecretRef:
      #     key: ""
      #     name: ""
      #     namespace: ""
      #   secretAccessKeySecretRef:
      #     key: ""
      #     name: ""
      #     namespace: ""
      #   sessionTokenSecretRef:
      #     key: ""
      #     name: ""
      #     namespace: ""
      # jwt:
      #   serviceAccountRef:
      #     name: ""

clusterExternalSecret:
  cloudflareOriginCAKey:
    enabled: true
    externalKeyName: ""
    secret:
      name: cloudflare-origin-ca-api-key
      key: token
