clusterSecretStore:
  oracle:
    enabled: true
    region: ""
    vaultOCID: ""
    tenancyOCID: ""
    userOCID: ""
    fingerprint: ""
    privateKey: ""
    privateKeyB64: ""

clusterExternalSecret:
  cloudflareCAAPIKey:
    externalKeyName: ""
    secret:
      name: cloudflare-ca-api-key
      key: cloudflare_origin_ca_key
