apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blackd
spec:
  description: Python code formatter
  sourceRepos:
    - https://charts.bhyoo.com
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: blackd
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
