apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
spec:
  description: Certificate manager
  sourceRepos:
    - https://charts.jetstack.io
    - https://charts.bhyoo.com
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: cert-manager
      name: backbone
    - namespace: kube-system
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
