apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
spec:
  description: Certificate manager
  sourceRepos:
    - https://charts.jetstack.io
    - https://charts.bhyoo.com
    - ghcr.io/cloudflare/origin-ca-issuer-charts
    - https://github.com/cloudflare/origin-ca-issuer.git
  destinations:
    - namespace: cert-manager
      name: prod
    - namespace: cert-manager
      name: backbone
    - namespace: origin-ca-issuer
      name: prod
    # some roles and role bindings require to access kube-system
    - namespace: kube-system
      name: prod
    - namespace: kube-system
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
