apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dfs
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Distributed Filesystem
  sourceRepos:
    - https://charts.rook.io/release
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: rook-ceph
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
