apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dns-manager
spec:
  description: Managing external DNS
  sourceRepos:
    - https://kubernetes-sigs.github.io/external-dns/
  destinations:
    - namespace: dns-manager
      name: backbone
    - namespace: dns-manager
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
