apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-controller
spec:
  description: Ingress controller of kubernetes cluster
  sourceRepos:
    - https://helm.traefik.io/traefik
  destinations:
    - namespace: kube-system
      name: backbone
    - namespace: kube-system
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
