apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-controller
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Ingress controller of kubernetes cluster
  sourceRepos:
    - https://helm.traefik.io/traefik
  destinations:
    - namespace: kube-system
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
