apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jay-stock-bot
spec:
  description: Jay's stock bot
  sourceRepos:
    - ghcr.io/jayjeong8/charts
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: jay-stock-bot
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
