apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: loadbalancer
spec:
  description: k8s LoadBalancer
  sourceRepos:
    - https://charts.bhyoo.com
  destinations:
    - namespace: loadbalancer
      name: backbone
    - namespace: loadbalancer
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
