# TODO: migrate to AppProject config when https://github.com/argoproj/argo-cd/issues/7799 is fixed
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: namespace-management
spec:
  description: Namespace management
  sourceRepos:
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: kube-system
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
