apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
spec:
  description: Cluster networking foundation (CNI, KPR, Gateway API, Hubble)
  sourceRepos:
    - https://helm.cilium.io/
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: kube-system
      name: backbone
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
