apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secret-manager
spec:
  description: Managing secret of kubernetes cluster
  sourceRepos:
    - https://charts.external-secrets.io
  destinations:
    - namespace: kube-system
      name: backbone
    - namespace: kube-system
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
