apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-upgrade
spec:
  description: Upgrading k8s system
  sourceRepos:
    - https://github.com/isac322/homelab.git
  destinations:
    - namespace: system-upgrade
      name: backbone
    - namespace: system-upgrade
      name: prod
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
