resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 10m
    memory: 32Mi

# where to assign node's internal ips (enum: ingress, external)
internalIPMappings:
  - external

# where to assign node's internal ips (enum: ingress, external)
externalIPMappings:
  - ingress

# IP networks that filters Ingress IP candidates out before assign. (e.g. 10.0.0.0/8 or 2603:c022:8005:302::/64)
excludeIngressIPNets:
  - 10.222.0.0/16
