apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blocky
spec:
  secretName: blocky-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - ByeonghoonYoo
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - dnsp.bhyoo.com
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
