apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-origin-ca-issuer-crds
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: cert-manager
  source:
    path: deploy/crds
    targetRevision: HEAD
    repoURL: https://github.com/cloudflare/origin-ca-issuer.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true