apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: secret-manager
  source:
    chart: external-secrets
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100