apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: secret-manager
  source:
    chart: sealed-secrets
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.1.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2