apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: ingress-controller
  source:
    chart: traefik
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/isac322/homelab/HEAD/values/traefik/backbone.yml
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.24.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: -1