apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-docker-io
  namespace: arc-systems
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
    proxy:
      remoteurl: https://registry-1.docker.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-docker-io
  namespace: arc-systems
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-ha-xfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-docker-io
  namespace: arc-systems
  labels:
    app: registry-docker-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-docker-io
  template:
    metadata:
      labels:
        app: registry-docker-io
    spec:
      containers:
        - name: registry
          image: docker.io/library/registry:2.8.3@sha256:a3d8aaa63ed8681a604f1dea0aa03f100d5895b6a58ace528858a7b332415373
          ports:
            - name: registry
              containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
              readOnly: true
            - name: data
              mountPath: /var/lib/registry
          readinessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: registry-docker-io
        - name: data
          persistentVolumeClaim:
            claimName: registry-docker-io
---
apiVersion: v1
kind: Service
metadata:
  name: registry-docker-io
  namespace: arc-systems
  labels:
    app: registry-docker-io
spec:
  selector:
    app: registry-docker-io
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
