{{- if .Values.podDisruptionBudget -}}
{{- if semverCompare ">=1.25-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "blackd.fullname" . }}
  labels:
    {{- include "blackd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "blackd.selectorLabels" . | nindent 6 }}
  minAvailable: {{ toYaml .Values.podDisruptionBudget.minAvailable | default "" }}
  maxUnavailable: {{ toYaml .Values.podDisruptionBudget.maxUnavailable | default "" }}
{{- end -}}
