apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare-gateway
spec:
  refreshInterval: 1h
  target:
    name: cloudflare-credentials
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /homelab/cluster/backbone/cloudflare/account-id
      secretKey: ACCOUNT_ID
    - remoteRef:
        key: /homelab/cluster/backbone/token/cloudflare/cloudflared-gateway
      secretKey: TOKEN
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
