apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  refreshInterval: 1h
  target:
    name: cloudflare-api-token
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - remoteRef:
        key: k8s_external_dns_api_token
      secretKey: cloudflare_api_token
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore