apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  refreshInterval: 1h
  target:
    name: cloudflare-api-token
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /homelab/cluster/backbone/token/cloudflare/external-dns
      secretKey: token
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
