image:
  repository: registry
  tag: 2.7.1
  pullPolicy: IfNotPresent
    # imagePullSecrets:
    # - name: docker

sealedSecret:
  auth: AgBK/WW6KhHoGoChzenkdVW9F/WDSmMRHDNxIhOJ/2Yt9KnG1ScNqj/3ygk7hZ8twLk/pOJ3kX/sTZbTs+oNsHE/CM3R9N2bOcp9jMMY/XxCTvAd58mkM1hX0iLaVgnnnlPPQ3FKBrb6ZaCO+0HeLZOWlFcIfbkOGoBbotmN/YyVNQB//CWrWZYcuzyIHXf+wAJqCWNKP45CBLCPaoA+k0BA8+T1nq3P/q7AWLrUk9nJoUAn19Gamcn/x5IsagJMTJO10g+WHEdlxs5Luk68k8BMyQAo/36oLn8EjG6kRWwb6jz7ohqXg+Mo+wzCnU3U0qR7gHa1NOzvCph4x7C0f84l6syl+2l3aJc+fJ8tWQ+gCoC3eUYLYTlDR4m/V0JQ9uUzCbTVQKnq48h2JxTZ8+PM6A45YJvPNzuEkA53jd4AuWZVzCAT4yXmbXIEDzGZwu35jJQE9hYa4zKIk/hjG8fLBKs6zIm9hKpIFzc6Vx6+tFBSjXVAAu0ymAzKCY4fDTBr6vV8yWqLm2Yvc956+UDIM0xzXu3+E2WoADAdnhYrW2q492SczC9vfL6foKh0aBJa18k47jT8mam0ZEhSJkE+rMIpqTHF1vpLWKDYrtFXoAnQEO93OLY8gj4bofSbLIa12x0tRj1CZvj4AwRJzDSAZNj4hGvgry4c1j+OBde6SuoFe4+mi0DUKKXADonwFPhMvuXOFfXQqooRE2Z8Ofyh6ql66At5YWVRAPJbKXKimWVtSJVSdP/ewKpwAJAOSZNVZz033rvCh/T0ARIlJnOs2uMZpd+F9yh5Z4TXABAOMF7KJz0QqsjC5KgCJ6A3uPoUO3+25lJh3ggfS5a8YDWb6TBHf99wGODXJldwGnBUKShDcQ==
  haSharedSecret: AgBajPrSCezsS50ykZAQ40S3cETpq7MF2WiX/ZXKIW1QMa0B6vkfN6kMSEdw2MBqohNztcO12BjyYek9h202YPp1OkgYnyP2wn3AFf3VyP3+pa0CBhKbzAgpvZPZcTYIFHCMMbbfRcz4Atbny6PInu+h6IpN/fVgFJcJtEwYd9MdE0PeXbgeML3Vfb4P7QR83xv8vNTkyjWZ1Ow70JiS0XdxG8wr0l6YzjoLhXdRh258oyMyvMLO+CfLAPSUbhDHbJ6CQ+Dj8pI9a+sD3/oAVYyKjLHOL2fvyPpOgCH6IOSbtsmXTJ54Xal8ATFQ4gpnmcUPnihAd9OrZe3HjCp8CBczS78f3i04vHiOVEXJu6Kv0DOTDTLZIAcy9zkkGm7Yz61Kzruaddk9fR8Xz+VZ4CQNupbjG2t/SKnCiUnf2u2fuoysP5v4u2gL8H83slF/75KvkUcPVYbvGd4IQ4P+NKlEfibcxWLbT9l/n73DPKz8N7HjMEvdUi9ADx9MbM1c3vZOfliHDGQ3snup1UmxrWqmNfednzEHn/jUL3erkO7RvnSU31lMp4GyUzRV2QgZVq/QD6qpK++DSlFY1L1EfpbnQkcj5u5DmqPssJZDkgn7pYsySjnrFCih8rO5sBlcC+ZIC/M4CNNGmXYwyPQFCB1BufIzS18je+NL2SY5lJXNC3Kl2mnKhDHN/DB1q5Rj+sH8Wel1z0Hmma2KxTnsvKQdgrcMKV1yJu/8H01WphBSHrObZXw=
  AWS_ACCESS_KEY_ID: AgAo3dCG+cXqc2SYyMZBYa/Uy9KY6zynOeCuc44l9wuHj0k/YnVOapLyh+q6Aw2X/mns9qqu8Gw+cxwzFI59Q6eQA6Nbk48KCP1y9OmRTKsblnTsqC8ajQ+m0qo3kgBWnPPV50r4bPGeazCUSeNFVW0kWBD7AnwAOClj6GwUHDq8i+VUb1+CO7aBKk8FhMi84aND3wKwK6eVp52pMMzFG7jsXAsUkcFZs6JuRkt7tzMnlf5nlrEzRKJYv0jTD/WZA7kT+2ePlohQdhlEUeZ0Q/dLyBkr5+RmPjiuuGJJEuNsP3XewgWOknkj0TW4ddx89jh5AmQPy+WrDEg0D5g1ktMXX4Vz1dBUnAIB5QHoxa9nkhaFa/V8k6s11KvaT/2XfxRuwnaqNA3QfVIb7XgZofTzEvQdFvOX116iGtZ/JONaZzuPw3J3dGf99wzwN/k6VaJsQRf+nMH6VQwjnlFaQdfrxyCGrMNOzEFDzafbxFCW3PyCHmFaUbXjkU7bDxZ2FPZiBwGYCbQBXPK7KwqbQXT0XIx4IFXncqhdu4wrv6Eh3s1xDXpqitEFo0HEbIisMKwSYu+14h8zQ6V914XzDhvqXZmPrIJtgbCSqGbIdgqk8eUTFvM+ldX7Mwa+bX1g7p8rJMlpxdzWe+UTzUjhJ3D5MNFuSTjRCx6U0PT/PanXHCVHb9b3kJjijWa5Sh2ehOdJY+xFtFWYgVigOM1w43bPU0Jf9BHI7/Mggv0dEIcTHC6KmEX6/OFt
  AWS_SECRET_ACCESS_KEY: AgDLMZOxiRK3gO0cR1t8PcQktI4SVeBclCqhCwEmKTwW5UPRaL0zraf7Bu+puwyvWjbohJuWPEBh0p15NlZ4V6yw402jbSzgBpTXYk8Z/i8ANR4P9xuMZTzTknTVr0zm7uiiXT4dLfvLeCQf9HFfFeQW40aqe1ob145OY7he5Y/qg5cHdSjkp8F2NCf/L6l1zB4jw4Fgh316A5+xkDvvIzRBTO7rDDY9CiiPGXjJ1MS5ZLWrAeyRjAV+Py7zXeWnfFY2sy3Cs+oj1gi05UWEUZGZ9VhHIRs8SeG+rapxgxEJZCDNezRpiU8xAG6SDSWHerUdk9/qjSV8EwMz0RNNEceeX09eQyNmaUo3l7mOUAb5pSsUxqLUCFHdljIxXclMqzvYAYX3QjWLtLLNcVNYazqSyE1BH1HtcOtR6nKjFN1n2SFOeO9yh30gO7WXZdWU9Y1FWxO/Ch38eFRfpIwDqxxlIbSEMH7ku7CTzJZmmR31zLfb3w84LkF/OA5PjcqNRU3QU0C0kn7WIFbAF6CrxwA+UXZwJK7YdjklB6v+2xEMMqtL5LKktb3/4uZX874MpxrUbcTBL98uEpDPHCsk03TSqQ7ZWkvkK2YHleIv60vfWhExno/YHlOHci0X30uo8C02xnlOqcgLFnYEVA0iDYnX5kVkbsmYNn20HUUylfiPFRh440+yZ6A4EZHO34D540Zf9+urze+UaVbzKf6TwH8E7I3i36w7erorPEU90+LV0ZcckY4KfjWHegbfug==

nodeSelector:
  oracle-instance-type: a1.flex

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    cert-manager.io/issuer: cloudflare-origin-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
  hosts:
    - host: registry.bhyoo.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - registry.bhyoo.com
      secretName: registry-com

storage:
  type: s3
  s3:
    encrypt: true
    bucket: registry
    regionEndpoint: "https://cnnw34eycsew.compat.objectstorage.ap-seoul-1.oraclecloud.com"
    region: ap-seoul-1
#  type: filesystem
#  persistence:
#    enabled: true
#    accessMode: ReadWriteOnce
#    size: 20Gi
#    storageClass: ceph-block
