PACKAGE_NAME="nvmet-tcp-target"
PACKAGE_VERSION="#MODULE_VERSION#"
AUTOINSTALL="yes"

source_tree="/usr/src/${PACKAGE_NAME}-${PACKAGE_VERSION}"
build_tree="${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"

if [[ -n "${kernelver:-}" ]]; then
  missing=$("${source_tree}/select-modules.sh" "$kernelver" target)
else
  missing="nvmet-tcp"
fi

if [[ -z "$missing" ]]; then
  BUILT_MODULE_NAME[0]="nvmet-tcp"
  BUILT_MODULE_LOCATION[0]="module/"
  DEST_MODULE_LOCATION[0]="/updates/dkms/"
  BUILD_EXCLUSIVE_KERNEL="a^"
else
  BUILT_MODULE_NAME[0]="nvmet-tcp"
  BUILT_MODULE_LOCATION[0]="module/"
  DEST_MODULE_LOCATION[0]="/updates/dkms/"
  PRE_BUILD="./prepare.sh ${kernelver} target ${missing} ${build_tree}/module"
  MAKE[0]="make -C /lib/modules/${kernelver}/build M=${build_tree}/module modules"
  CLEAN="make -C /lib/modules/${kernelver}/build M=${build_tree}/module clean"
fi
