name: Terraform

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  backbone:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.0
        with:
          files: terraform/backbone/**/*.tf
      - name: Terraform
        if: steps.changed-files.outputs.any_changed == 'true' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
        uses: ./.github/actions/terraform
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          path: terraform/backbone

  prod:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.0
        with:
          files: terraform/prod/**/*.tf
      - name: Terraform
        if: steps.changed-files.outputs.any_changed == 'true' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
        uses: ./.github/actions/terraform
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          path: terraform/prod