name: Terraform

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cluster-setup:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          files: cluster-setup/terraform/**/*.tf
      - name: Terraform
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/terraform
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          path: cluster-setup/terraform
  backbone:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          files: terraform/backbone/**/*.tf
      - name: Terraform
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/terraform
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          path: terraform/backbone