name: Terraform

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

jobs:
  backbone:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            1-provision/env/backbone/**/*.tf
            1-provision/modules/dns-secrets/**/*.tf
      - name: Terraform
        if: steps.changed-files.outputs.any_changed == 'true' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
        uses: ./.github/actions/terraform
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          path: 1-provision/env/backbone

  prod:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            1-provision/env/prod-vultr/**/*.tf
            1-provision/modules/dns-secrets/**/*.tf
            1-provision/modules/vultr-cluster/**/*.tf
      - name: Terraform
        if: steps.changed-files.outputs.any_changed == 'true' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
        uses: ./.github/actions/terraform
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          path: 1-provision/env/prod-vultr
