certificate:
  type: cert-manager
  spec:
    secretName: &secretName blocky-cert
    duration: 2160h # 90d
    renewBefore: 360h # 15d
    subject:
      organizations:
        - ByeonghoonYoo
    privateKey:
      algorithm: ECDSA
      size: 384
    dnsNames:
      - &host dnsb.bhyoo.com
    issuerRef:
      name: cluster-issuer-acme
      kind: ClusterIssuer

dns:
  service:
    type: LoadBalancer
    annotations:
      static-lb.bhyoo.com/exclude-ingress-ip-nets: ""
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      external-dns.alpha.kubernetes.io/exclude: "true"
    externalTrafficPolicy: Local

dot:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      external-dns.alpha.kubernetes.io/hostname: *host
      static-lb.bhyoo.com/internal-ip-mappings: ingress
      static-lb.bhyoo.com/external-ip-mappings: external
      static-lb.bhyoo.com/exclude-external-ip-nets: 10.222.0.0/16
      external-dns.alpha.kubernetes.io/exclude: "true"
    externalTrafficPolicy: Local

doh:
  enabled: false
  tlsTerminationOn: app
  service:
    enabled: true
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      external-dns.alpha.kubernetes.io/exclude: "true"
    hosts:
      - *host
    tlsSecretName: *secretName

upstreams:
  # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
  # format for resolver: [net:]host:[port][/path]. net could be empty (default, shortcut for tcp+udp), tcp+udp, tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
  # this configuration is mandatory, please define at least one external DNS resolver
  defaultUpstreams:
    - tcp-tls:1.1.1.1
    - tcp-tls:1.0.0.1
#    - tcp-tls:dns-s.safedns.com
#    - tcp-tls:security-filter-dns.cleanbrowsing.org

  startVerify: true

blocking:
  customize: true

  denylists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://hosts.oisd.nl/
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      - https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/domains.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Apple-AdBlock.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://raw.githubusercontent.com/What-Zit-Tooya/Ad-Block/main/Main-Blocklist/Ad-Block-Simplified.txt
      - https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt
    annoyance:
      - https://gitlab.com/quidsup/notrack-annoyance-blocklist/raw/master/annoyance.list
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
    spotify_ad:
      - https://gist.githubusercontent.com/opus-x/3e673a9d5db2a214df05929a4eee6a57/raw/Spotify_Eliminate_Advertisements
    korean:
      - https://github.com/yous/YousList/raw/master/youslist.txt
      - https://raw.githubusercontent.com/Apious/Ads_Filter_DNS/HEAD/Ads_Filter_DNS.txt
      - https://cdn.jsdelivr.net/gh/adguardteam/HostlistsRegistry@main/assets/filter_25.txt
    tracker:
      - https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/trackers.list
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
    malware:
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/malware.list
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
    fakenews:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
    mining:
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts
    all:
      - |
        /.*/
  allowlists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - |
        sentry.io
        sentry-cdn.com
        thepiratebay.org
    trackers:
      - |
        sentry.io
  clientGroupsBlock:
    default:
      - ads
      - annoyance
      - spotify_ad
      - korean
      - tracker
      - malware
      - fakenews
      - mining
    hackers:
      - all

  loading:
    downloads:
      timeout: 10m
    maxErrorsPerSource: -1
    concurrency: 20

filtering:
  customize: true
  queryTypes:
    - AAAA

caching:
  customize: true
  prefetching: true
  minTime: 5s

redis:
  enabled: false
  blocky:
    required: false
  auth:
    password: some-password
  master:
    persistence:
      size: 512Mi
      storageClass: ceph-block
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

ede:
  enable: true

prometheus:
  serviceMonitor:
    enabled: true

clientLookup:
  customize: true
  clients:
    hackers:
      - 95.216.117.41
      - 95.216.226.168
      - 51.158.79.226
      - 213.168.249.75
      - 5.189.191.107
      - 183.136.225.5
      - 163.172.152.35
      - 142.93.73.210 # US
      - 154.12.228.10 # US
      - 51.158.102.250
      - 51.15.128.38
      - 51.15.193.80
      - 51.15.209.16
      - 51.15.239.123
      - 79.137.194.107
      - 51.158.67.126
      - 3.101.216.80 # US
      - 68.183.29.9 # US
      - 3.134.5.68 # US
